include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: 
    - build/**
    - ios/**
    - android/**
    - web/**
    - mac/**

    # Ignore generated files
    - '**/*.g.dart'

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: warning
    