name: home
description: >-
  Home Assistant Companion for iOS, Android, Web and MacOS.
  Interacts with cedricgrothues/home-automation's API.

version: 0.1.0+5
author: Cedric Grothues <cedricgrothues@gmail.com>

repository: https://www.github.com/cedricgrothues/home-automation

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Effective Dart (Static analysis)
  pedantic: ^1.9.0

  # Commonly used locations on the filesystem
  path_provider: ^1.6.0

  # Open URLs
  url_launcher: ^5.4.1

  # Used to check if the user is connected to Wifi
  connectivity: ^0.4.6+2

  # HTTP Requests
  http: ^0.12.0+4

  # Data Storage
  hive: ^1.3.0

  # JSON Parsing
  json_annotation: ^3.0.1

dev_dependencies:
  # JSON Parsing
  json_serializable: ^3.2.5

  # Used to autogenerate JSON files
  build_runner: ^1.7.3

flutter:
  uses-material-design: true

  assets:
    - assets/themes/
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

publish_to: none
