name: service.device.registry
description: A device-registry service
version: 1.0.0

author: Cedric Grothues <cedricgrothues@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  router:
    path: ../libraries/router
