version: '3.7'

services:
  # core - Required for the hub to work properly
  core.api-gateway:
    container_name: "core.api-gateway"
    restart: always
    build:
     dockerfile: ./core/api-gateway/Dockerfile
     context: .
    ports:
      - 4000:4000

  core.device-registry:
    container_name: "core.device-registry"
    restart: always
    build:
      dockerfile: ./core/device-registry/Dockerfile
      context: .
    ports:
      - 4001:4001
    depends_on:
      - core.persistence

  core.user:
    container_name: "core.user"
    restart: always
    build:
      dockerfile: ./core/user/Dockerfile
      context: .
    ports:
      - 4002:4002
    depends_on:
      - core.persistence

  core.persistence:
    container_name: "core.persistence"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zuhkiz-2honwu-semhoV
      - POSTGRES_DB=core.persistence
    ports:
      - 5432:5432
    volumes:
      - ./core/persistence/init.sql:/docker-entrypoint-initdb.d/init.sql
      - core.persistence.data:/var/lib/postgresql/data

  # modules - Not required
  modules.scene:
    container_name: "modules.scene"
    restart: always
    build:
      dockerfile: ./modules/scene/Dockerfile
      context: .
    ports:
      - 4006:4006
    depends_on:
      - core.persistence

  modules.sonoff:
    container_name: "modules.sonoff"
    restart: always
    build:
      dockerfile: ./modules/sonoff/Dockerfile
      context: .
    ports:
      - 4003:4003
    depends_on:
      - core.device-registry

#  modules.sonos:
#    container_name: "modules.sonos"
#    restart: always
#    build:
#      dockerfile: modules.sonos/Dockerfile
#      context: .
#    ports:
#      - 4004:4004
#    depends_on:
#      - core.device-registry

  modules.aurora:
    container_name: "modules.aurora"
    restart: always
    build:
      dockerfile: ./modules/aurora/Dockerfile
      context: .
    ports:
      - 4005:4005
    depends_on:
      - core.device-registry


volumes:
  core.persistence.data:
