version: '3'

services:
  service.controller.plug:
    build:
      dockerfile: ./service.controller.plug/dev.dockerfile
      context: .
    volumes:
      - ./service.controller.plug:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8001:80
    environment:
      NODE_ENV: production
    env_file:
      - ./.env