version: '3.7'

services:
  # core
  core.api-gateway:
    restart: always
    build:
     dockerfile: ./modules/api-gateway/Dockerfile
     context: .
    ports:
      - 4000:4000

  core.device-registry:
    restart: always
    build:
      dockerfile: ./modules/device-registry/Dockerfile
      context: .
    ports:
      - 4001:4001
    depends_on:
      - core.persistence.database

  core.persistence.database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zuhkiz-2honwu-semhoV
      - POSTGRES_DB=core.persistence.database
    ports:
      - 5432:5432
    volumes:
      - ./core/persistence/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - core.persistence.database.data:/var/lib/postgresql/data

  # modules
  modules.sonoff:
    restart: always
    build:
      dockerfile: ./modules/sonoff/Dockerfile
      context: .
    ports:
      - 4002:4002
    depends_on:
      - core.device-registry
      
#  modules.sonos:
#    container_name: "modules.sonos"
#    restart: always
#    build:
#      dockerfile: modules.sonos/Dockerfile
#      context: .
#    ports:
#      - 4003:4003
#    depends_on:
#      - core.device-registry

  modules.aurora:
    restart: always
    build:
      dockerfile: ./modules/aurora/Dockerfile
      context: .
    ports:
      - 4004:4004
    depends_on:
      - core.device-registry


volumes:
  core.persistence.database.data: