name: service.controller.plug
description: Dart controller for smart plugs.
version: 1.0.0
author: Cedric Grothues <cedricgrothues@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  router:
    path: ../libraries/router
