name: home
description: The mobile, web and desktop application communicating with the cedricgrothues/home-automation api

version: 0.1.0-alpha

repository: https://www.github.com/cedricgrothues/home-automation

author: Cedric Grothues <cedricgrothues@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.2.5
  provider: ^3.1.0+1
  connectivity: ^0.4.5+3
  http: ^0.12.0+2
  shared_preferences: ^0.5.4+5
  json_annotation: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.3
    
      

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family:  Regular
      fonts:
        - asset: assets/fonts/Regular.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/Light.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

publish_to: none
