port: 4000

services:
    service.device-registry:
        name: Device Registry
        prefix: service.device-registry
        upstream: http://127.0.0.1:4001
    service.controller.sonoff:
        name: Sonoff Controller
        prefix: service.controller.sonoff
        upstream: http://127.0.0.1:4002
    service.controller.sonos:
        name: Sonos Controller
        prefix: service.controller.sonos
        upstream: http://127.0.0.1:4003