port: 4000

services:
    service.device-registry:
        name: Device Registry
        prefix: service.device-registry
        upstream: http://service.device-registry:4001
    service.controller.sonoff:
        name: Sonoff Controller
        prefix: service.controller.sonoff
        upstream: http://service.controller.sonoff:4002
    service.controller.sonos:
        name: Sonos Controller
        prefix: service.controller.sonos
        upstream: http://service.controller.sonos:4003
    service.controller.aurora:
        name: Nanoleaf Aurora Controller
        prefix: service.controller.aurora
        upstream: http://service.controller.aurora:4004