name: hub
description: The home-automation cli for interacting with your home hub

version: 0.1.0-alpha
homepage: https://github.com/cedricgrothues/home-automation
author: Cedric Grothues <cedricgrothues@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.2

dev_dependencies:
  test: ^1.6.0
